# Generated by Django 4.2.4 on 2024-10-22 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shavtzak_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSystemCustomFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('entity_initializer', 'Entity Initializer'), ('shavtzak_manager', 'Shavtzak Manager'), ('regular_user', 'Regular User')], default='regular_user', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_system_custom_fields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
